SisSerSocMedHumUAZ-master/mensajeria/urls.py
from django.conf.urls import url

from . import views

app_name ='message'
urlpatterns = [
    url(r'^$', views.enviarMensaje, name='enviarMensaje'),
    url(r'^guardar_mensaje/$', views.registrarDatos, name='guardar_mensaje'),

    
]

SisSerSocMedHumUAZ-master/rol/urls.py
from django.conf.urls import url

from rol.views import *

urlpatterns = [
    url(r'^registrar_rol/$', CrudRol.registrar_rol, name="registrar_rol"),
    url(r'^modificar_rol/$', CrudRol.modificar_rol, name="modificar_rol"),
    url(r'^roles/$', CrudRol.mostrar_roles, name="roles"),
    url(r'^eliminar_rol/$', CrudRol.eliminar_rol, name="eliminar_rol"),
    url(r'^tutores/$', CrudTutor.mostrar_tutores, name="tutores"),
    url(r'^eliminar_tutor/$', CrudTutor.eliminar_tutor, name="eliminar_tutor"),
    url(r'^modificar_tutor/$', CrudTutor.modificar_tutor,
        name="modificar_tutor"),
    url(r'^registrar_tutor/$', CrudTutor.registrar_tutor,
        name="registrar_tutor"),
    url(r'^asignar_rol/$', AsignacionRolPasante.asignar_rol,
        name='asignar_rol'),
    url(r'^rol_pasante_json/$', AsignacionRolPasante.rol_pasante_json,
        name='rol_pasante_json'),
    url(r'^modificar_asignacion/$', AsignacionRolPasante.modificar_asignacion,
        name='modificar_asignacion'),
    url(r'^carta_asignacion/$', AsignacionRolPasante.carta_asignacion,
        name='carta_asignacion'),
    url(r'^clinicas_institucion/$', obtener_clinicas),
    url(r'^carta_asignacion_oficial/$',
        AsignacionRolPasante.carta_asignacion_oficial,
        name='carta_asignacion_oficial'),
    url(r'configuracion_asignacion', AsignacionRolPasante.configurar_asignacion,
        name='configuracion_asignacion'),
]

SisSerSocMedHumUAZ-master/ssmh_uaz_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from contactos_pasante import  views



urlpatterns = [
    url(r'^chat/', include('mensajeria.urls')),
    url(r'^', include('usuario.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^Pasante/',include('pasante.urls')),
    url(r'^Coordinador/',include('coordinador.urls')),
    #url(r'^SuperUsuario/',include('SuperUsuario.urls')),
    url(r'^Rol/',include('rol.urls')),
    url(r'^foro/',include('foro.urls')),
    url(r'^Pregunta/',include('pregunta.urls')),

    url(r'^api/contacto/obtenerContactos/(?P<idPasante>.+)/$', views.GetContactos.as_view(), name='obtener_contactos'),
    url(r'^api/contacto/insertarContacto', views.InsertContacto.as_view(), name='insertar_contacto'),
    url(r'^api/contacto/eliminarContacto/(?P<idContacto>[0-9]+)/$', views.EliminarContacto.as_view(), name='eliminar_contacto'),
    url(r'^api/contacto/actualizarContacto/(?P<idContacto>[0-9]+)/$', views.ActualizarContacto.as_view(), name='actualizar_contacto'),
    url(r'^api/usuario/verificarUsuario/$', views.VerificarUsuario.as_view(), name='verificar_usuario'),
    url(r'^api/usuario/activaralerta$', views.ActivarAlerta.as_view(), name='alerta'),
    url(r'^api/usuario/informacionPasante/$', views.InformacionPasante.as_view()),
    url(r'^api/usuario/enviarMensaje/$', views.EnviarMensaje.as_view(), name='Enviar Mensaje'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SisSerSocMedHumUAZ-master/mensajeria/models.py
from django.db import models
from clinica.models import Clinica
from pasante.models import Pasante,Generacion,Promocion
from django.contrib.auth.models import User
from django.urls import reverse
from coordinador.models import CatalogoTipoInconformidad
from coordinador.models import Coordinador
from collections import OrderedDict


'''class Tema(models.Model):
    nombre_tema= models.CharField(null=True, max_length=50)

    def __str__(self):
        return (str(self.nombre_tema))'''



class Pregunta(models.Model):
    id_pregunta = models.AutoField(primary_key=True)
    pregunta= models.CharField(null=True, max_length=150, unique=True)
    respuesta = models.CharField(null=True, max_length=150)
    id_tipo_fk_id= models.ForeignKey(CatalogoTipoInconformidad, on_delete=models.CASCADE,verbose_name='Tema')#Nuevo
    coordinador= models.ForeignKey(Coordinador, on_delete=models.CASCADE)#Nuevo


class Mensaje(models.Model):
    id_mensaje = models.AutoField(primary_key=True)
    fecha_inicio= models.DateTimeField()
    fecha_final= models.DateTimeField()
    id_tipo_fk_id = models.ForeignKey(CatalogoTipoInconformidad, on_delete=models.CASCADE)
    texto= models.TextField(default=" ")
    id_pasante_fk_id= models.ForeignKey(Pasante, on_delete=models.CASCADE)
    id_coordinador_fk_id=models.ForeignKey(Coordinador, on_delete=models.CASCADE)
    id_clinica_fk_id=models.ForeignKey(Clinica, on_delete=models.CASCADE)
    promocion = models.ForeignKey(Promocion, on_delete=models.CASCADE)#Nuevo
    leido= models.BooleanField(default=1)


class conversacion(models.Model):
    id_mensaje = models.AutoField(primary_key=True)
    fecha_inicio= models.DateTimeField()
    fecha_final= models.DateTimeField()
    id_tipo_fk_id = models.ForeignKey(CatalogoTipoInconformidad, on_delete=models.CASCADE)
    importante = models.BooleanField(default=1)
    id_pasante_fk_id= models.ForeignKey(Pasante, on_delete=models.CASCADE)
    id_coordinador_fk_id=models.ForeignKey(Coordinador, on_delete=models.CASCADE)
    id_clinica_fk_id=models.ForeignKey(Clinica, on_delete=models.CASCADE)
    promocion = models.ForeignKey(Promocion, on_delete=models.CASCADE)#Nuevo
    leido= models.BooleanField(default=1)

class mensaje_Conversacion(models.Model):
    id_mensaje = models.AutoField(primary_key=True)
    id_conversacion_fk_id = models.ForeignKey(conversacion,on_delete=models.CASCADE)
    mensaje=models.TextField(default=" ")
    resaltado=models.BooleanField(default=False)

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.trainers import Trainer
from chatterbot.conversation import Statement, Response
from mensajeria.views import Entrenador



chatbot = ChatBot(
    "faqsBot",

    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    database='./faqsBotDB.sqlite3',
    input_adapter="chatterbot.input.VariableInputTypeAdapter",
    output_adapter="chatterbot.output.OutputAdapter",
    output_format="text",
    #trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
    trainer= 'mensajeria.views.Entrenador',
    filters=["chatterbot.filters.RepetitiveResponseFilter"],


    logic_adapters=[

        {
            "import_path": "chatterbot.logic.BestMatch",
            "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance",
            "response_selection_method": "chatterbot.response_selection.get_most_frequent_response"
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.65,
            "response_selection_method": "chatterbot.response_selection.get_most_frequent_response",
            'default_response': 'Espera un momento, tu mensaje será enviado a un coordinador.'
        },

    ],

    preprocessors=[
        'chatterbot.preprocessors.clean_whitespace',

    ],

    read_only = False,
)

preguntasFreq = [" ",]
no_repetidos = []
conversaciones = []

def entrenar_bot():
    preguntas= Pregunta.objects.all()
    for p in preguntas:
        conversaciones.append(p.pregunta)
        conversaciones.append(p.respuesta)

    no_repetidos = list(OrderedDict.fromkeys(conversaciones))
    chatbot.train(no_repetidos)
    print (no_repetidos)

SisSerSocMedHumUAZ-master/mensajeria/views.py
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe
import json
from mensajeria.models import Mensaje, conversacion, mensaje_Conversacion
from pasante.models import Pasante,Generacion,Promocion
from usuario.models import Usuario
from clinica.models import Clinica
from coordinador.models import CatalogoTipoInconformidad
from rol.models import AsignacionRol
from coordinador.models import Coordinador
from chatterbot.trainers import Trainer
from chatterbot.conversation import Statement, Response
from chatterbot import utils
import sys


from django.contrib.auth.models import User
from datetime import datetime, timedelta , date
import re
importante = False

class Entrenador(Trainer):
    
    def train(self, conversation):
        """
        Train the chat bot based on the provided list of
        statements that represents a single conversation.
        """
        previous_statement_text = None#ahora es la pregunta
        #esPregunta = True
        for conversation_count, text in enumerate(conversation):
            if self.show_training_progress:
                utils.print_progress_bar(
                    'Entrenador',
                    conversation_count + 1, len(conversation)
                )
            #if esPregunta:
            statement = self.get_or_create(text)#genera la pregunta
            #   esPregunta = False
            #else:
            #    response = self.get_or_create(text)
            #    esPregunta = True

            if previous_statement_text and conversation_count % 2 == 1:
                statement.add_response(
                    Response(previous_statement_text)
                )
            #Aqui esta el error, hay que intentar agregar las preguntas en impares y las respuestas
            #en pares
            #genera la repuesta
            #if conversation_count % 2 == 1:
            previous_statement_text = statement.text                
            self.storage.update(statement)
            #else:
            #    previous_statement_text = None
            #    self.storage.update(statement)

def enviarMensaje(request):

    pk_mensaje= None
    is_coordinador=0
    mensaje=""
    #tipo_user = Usuario.tipo_usuario
    #nombreChat=Pasante.objects.get(id_usuario_fk= Usuario.objects.get(matricula=request.user.username)) 
    coordinador = Coordinador.objects.get(matricula= Usuario.objects.get(username='11111111'))
    #nombre_conexion=request.POST.get('matricula_pasante')
    if request.user.is_staff: #si es coordindor
        nombre_conexion = request.POST.get('matricula_pasante') #obtiene la matricula del pasante

        # si hay pk_mensaje es un coordinador y se envia el pk por contexto para actualizar la tabla en la siguiente funcion
        pk_mensaje=request.POST.get('pk_mensaje')
        mensaje=Mensaje.objects.get(id_mensaje=(pk_mensaje))
        #mensaje=Mensaje.objects.get(id_mensaje=(request.POST.get()))
        mensaje= str(mensaje.texto) + "\n"

        is_coordinador=1
    else:
        nombre_conexion=request.user.username
        print(request.POST.get('matricula_pasante'))
           #si es pasante se utiliza su matricula para la conexion
        pasante=Pasante.objects.get(id_usuario_fk= Usuario.objects.get(matricula=request.user.username))
    	#si es pasante se guarda el mensaje para que el coordinador lo pueda ver luego
        myDate = datetime.now()
        f_inicial = myDate.strftime("%Y-%m-%d %H:%M:%S")
        asignacion= AsignacionRol.objects.get(id_pasante=pasante)
        
        clinica = asignacion.id_rotacion.id_clinica_fk
        promocion1=Promocion.objects.get(id_pasante_fk=pasante.id_pasante)
        tema_mensaje= CatalogoTipoInconformidad.objects.get(id_tipo=1)  #escoger el tema por defecto
        m1= Mensaje.objects.create(fecha_inicio=f_inicial, fecha_final=f_inicial, id_tipo_fk_id=tema_mensaje, id_pasante_fk_id=pasante,
            id_coordinador_fk_id= coordinador, id_clinica_fk_id=clinica,promocion=promocion1, leido=False, texto="" )
        
        #pk_mensaje=request.POST.get('pk_mensaje')
        
        pk_mensaje=m1.pk
        #mensaje=Mensaje.objects.get(id_mensaje=(pk_mensaje))
        #mensaje= str(mensaje.texto) + "\n"
        print("mensaje pk ...................")
        print(pk_mensaje)



    obtenerTemas=CatalogoTipoInconformidad.objects.all()
    
    return render(request, 'mensajeria/mensajeria.html', {'temas':obtenerTemas,'pk_mensaje':pk_mensaje, 'texto_mensaje':mensaje,
        'is_coordinador':is_coordinador, 'usuario': mark_safe(json.dumps(nombre_conexion))
    })


def registrarDatos(request):
    if (request.method=='POST'):
        esImportante=request.POST.get("es_importante","0")
        varImportante = False
        if esImportante == str(1):
            varImportante = True
        print(varImportante)
        pk_mensaje=request.POST.get('pk_mensaje')
        mensaje=Mensaje.objects.get(id_mensaje=(pk_mensaje))
        mensaje.leido=True
        mensaje.save()
        ultima_conver= conversacion.objects.latest('id_mensaje')
        if mensaje.fecha_inicio != ultima_conver.fecha_inicio:
	        m2= conversacion.objects.create(fecha_inicio=mensaje.fecha_inicio, fecha_final=mensaje.fecha_final, id_tipo_fk_id=mensaje.id_tipo_fk_id, importante=varImportante, id_pasante_fk_id=mensaje.id_pasante_fk_id,
	            id_coordinador_fk_id=mensaje.id_coordinador_fk_id, id_clinica_fk_id=mensaje.id_clinica_fk_id,promocion=mensaje.promocion, leido=True )
	        print(str(mensaje.texto))
	        mensajitos = str(mensaje.texto)
	        men =  re.split('\n',mensajitos)
	        indi=2
	        while indi<len(men):
	        	m3= mensaje_Conversacion.objects.create(id_conversacion_fk_id=conversacion.objects.latest('id_mensaje'),mensaje=men[indi])
	        	indi= indi + 3

    return redirect("/")

    

SisSerSocMedHumUAZ-master/mensajeria/templates/mensajeria/fecha.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
    <input id="chat-message-submit" type="button" value="Send"/>


<script type="text/javascript">

document.querySelector('#chat-message-submit').onclick = function(e) {
	var d = new Date();
alert((' '+ d.getMonth()+'/'+d.getDay()+ '/' + d.getFullYear()+' '+d.getHours()+':'+d.getMinutes()));
}
</script>




</body>
</html>

SisSerSocMedHumUAZ-master/mensajeria/templates/mensajeria/mensajeria.html
{% extends 'base.html' %}
{% load filtros %}
{% load staticfiles %}

{% comment "Esto es por si se quiere cambiar los extends y poner la interface en el chat con el menu del coordinador, solo que si se pone uno se afecta al otro, por los estilos que estan"%}

{% if user.is_authenticated %}
    {% if request.user.is_active and request.user.is_staff %}

    {% include 'base_coordinador.html' %}
    {% load filtros %}
    {% load staticfiles %}

    {% endif %}
{% endif %}

<!-- Esto es para el pasante  -->
{% if user.is_authenticated %}
    {% if request.user.is_active and not request.user.is_staff %}

        {% include 'base.html' %}
        {% load filtros %}
        {% load staticfiles %}

        {% extends request.user.is_staff | yesno: "base_coordinador.html, base.html"%}

    {% endif %}
{% endif %}

{% endcomment %}

{% block imagen %}
    width: 100%;
    height: 100%;
    background-image: url(/static/img/bodybg/bg1.png);
    background-attachment: fixed;
{% endblock %}


{% block menu %}
{% load filtros %}
{% load staticfiles %}

    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><STRONG><font size="2">NORMATIVIDAD</font></STRONG>
            <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url "mostrar_normatividad" %}" onclick="terminar()">Mostrar Normatividad</a></li>
                    <li><a href="{% url "ver_normatividad" %}" onclick="terminar()">Ver Normatividad</a> </li>
                    <li><a href="{% url "buscar_normatividad"%}" onclick="terminar()">Buscar Tema en Normatividad</a></li>
                </ul>
    </li>


    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><STRONG><font size="2">REPORTES</font></STRONG>
            <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url "reporte_inconformidad_pasante" 6 0 %}" onclick="terminar()">Ver Reportes</a></li>
                        {% if entre_fechas %}
                            <li><a href="{% url "reporte_in"%}" onclick="terminar()" > Reporte de Inconformidad  </a>  </li>
                        {% endif %}
                </ul>
    </li>

    





{% endblock %}


{% block panico %}
{% load filtros %}
{% load staticfiles %}
<li>
 <a href="{% url "activar_alerta" %}"><STRONG><font size="2">ALERTA</font></STRONG></a></li>
 <li class="dropdown"><a
    href="{% url "message:enviarMensaje" %}"style="margin-top: 1px;"><STRONG><font
    size="2">MENSAJERÍA</font></STRONG></a>
</li> 
{% endblock %}


{% block titulo %}
{% load filtros %}
{% load staticfiles %}

Mensajería
<button class="btn btn-primary btn-xs" style="float:right;" id="btn_importante" onclick="marcarImportante()" >Importante</button>


{% endblock %}




{% block contenido %}
{% load filtros %}
{% load staticfiles %}

<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Mensajeria SSMH</title>
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/alertify.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/alertify.min.css"/>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/themes/default.min.css"/>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/themes/semantic.min.css"/>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/themes/bootstrap.min.css"/>
</head>
<body>

<style>
    div.justified {
        display: flex;
        justify-content: center;
    }

    textarea {

    resize: vertical;

    }


</style>
<style>
.wrapper {
    text-align: center;
}

.button {
    position: absolute;
    top: 50%;
}
</style>

     <div class="justified">  
    <select style="
                       height: 34px;
                       width: 97.5%;
                       padding: 6px 12px;
                       font-size: 14px;
                       line-height: 1.42857143;
                       color: #555;
                       background-color: #fff;
                       background-image: none;
                       border: 1px soli d #ccc;
                       border-radius: 4px; margin-left: 10px;
                      " id="tema_seleccionado" name="tema_seleccionado" onchange ="seleccionarTema(this)">
        <option value="">Selecciona tema de conversación</option>
        {% for tema in temas %}
                    <option value="{{tema.nombre}}"> {{tema.nombre}} </option>
        {% endfor %}
    </select>
    
    </div>


    <form name="finalizar" id="fin_form" method="post" action="{% url 'message:guardar_mensaje'  %}">
        {% csrf_token %}
        <input type="hidden" id="pk_mensaje" name="pk_mensaje" value="{{pk_mensaje}}">
        <input type="hidden" id="es_importante" name="es_importante" value="">
    </form>

    <div class="justified">
    {% if is_coordinador == 1 %}
        <textarea class="textarea col-75" id="texto_mensaje" readonly style="width:98%; height:50%;"  > {{texto_mensaje}}</textarea><br/>
        {% else %}
        <textarea class="textarea col-75" placeholder="&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  Iniciado como: {{user.username}}" id="texto_mensaje" readonly style="width:98%; height:50%;" >{{texto_mensaje}}</textarea><br/>
    {% endif %}
     </div>

    <div class="justified">
    <input placeholder="Escribe un mensaje..." align="middle" id="txt_enviar_mensaje" type="text" style="width:83%;" autofocus onclick="addContent()"/><input class="btn btn-primary btn-xs" style="margin-right:10px;"  id="enviarMensaje" type="button" value="Enviar"/><br/>
     <button class="btn btn-primary btn-xs" style="margin-bottom:1px;" id="btn_finalizar" onclick="terminar()" >Finalizar</button>
    </div>    

    
</body>

<style>
* {
    box-sizing: border-box;
}

input[type=text], textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    resize: vertical;
}

label {
    padding: 12px 12px 12px 0;
    display: inline-block;
}

input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    float: right;
}

input[type=submit]:hover {
    background-color: #45a049;
}

.container2 {
    border-radius: 5px;
    padding: 20px;
}

.col-25 {
    float: left;
    width: 25%;
    margin-top: 6px;
}

.col-75 {
    float: center;
    width: 75%;
    margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
    .col-25, .col-75, input[type=submit] {
        width: 100%;
        margin-top: 0;
    }
}
</style>



<script>
    
    var tema_seleccionado="";
    var d = new Date();
    var pk_mensaje={{pk_mensaje}};
    var tipo_user;// = {{tipo_user}};
    
    var is_coordinador={{is_coordinador}};
    
    if (is_coordinador==1){
        tipo_user="coordinador";
        document.getElementById("tema_seleccionado").style.visibility = "hidden";
    }else{
        tipo_user="pasante";

    document.getElementById("btn_importante").style.visibility = "hidden"
    document.getElementById("tema_seleccionado").disabled = false;
    document.getElementById("btn_finalizar").disabled = true;
    document.getElementById("texto_mensaje").disabled = true;
    document.getElementById("txt_enviar_mensaje").disabled = true;
    document.getElementById("enviarMensaje").disabled = true;


    function seleccionarTema(objeto){

        tema_seleccionado= objeto.options[objeto.selectedIndex].value;
        document.getElementById("tema_seleccionado").disabled = false;//true
        document.getElementById("btn_finalizar").disabled = false;
        document.getElementById("texto_mensaje").disabled = false;
        document.getElementById("txt_enviar_mensaje").disabled = false;
        document.getElementById("enviarMensaje").disabled = false;
 
    }

    }

    function marcarImportante(){
        document.getElementById("btn_importante").style.background='rgb(183, 149, 11)';
        document.getElementById('es_importante').value = 1
    }


    function terminar(){
       alertify.confirm('¿Está seguro de que desea finalizar?', 'Al finalizar la conversación ya no se podrá continuar después.', function(){ document.getElementById('fin_form').submit(); }
                , function(){ alertify.error('Cancelado')});
    }

    function enviarInicio(e){
        alertify.alert('Usuario desconectado','El usuario con el que estabas conversando se ha desconectado', 
        function(){
            
            if(e){
                
                document.getElementById('fin_form').submit();
            }else{
                
                document.getElementById('fin_form').submit();
            }  
        }
        );
    }
    //var usuario = {{user.use}}; //{{ user.username }};

    document.querySelector('#txt_enviar_mensaje').focus();
    document.querySelector('#txt_enviar_mensaje').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#enviarMensaje').click();
        }
    };
        
    var usuario = {{usuario}};
    var chatSocket = new WebSocket('ws://' + window.location.host +'/ws/chat/' + usuario + '/');
    //console.log("Conected to:" + usuario);
    document.querySelector('#enviarMensaje').onclick = function(e) {
        document.getElementById("tema_seleccionado").disabled = true;
        var d = new Date();
        //var roomCreado = 0;
        fecha_actual=(' '+ d.getMonth()+'/'+d.getDay()+ '/' + d.getFullYear()+' '+d.getHours()+':'+d.getMinutes());
        var messageInputDom = document.querySelector('#txt_enviar_mensaje');
        /*if(messageInputDom.value == "Usuario se ha desconectado"+"\n"){
            enviarInicio();
        }*/
        if (messageInputDom.value == "") {

            alertify.set('notifier','position', 'top-center');
            //alertify.warning('No se pueden enviar mensajes en blanco');
            alertify.notify('No se pueden enviar mensajes en blanco', 'warning', 2, function(){  console.log('dismissed'); });


            return false
        }

        
        //var elMensaje
  
        //document.querySelector('#texto_mensaje').value += (message + '\n');
  
        


        var message = messageInputDom.value;
        var user={{user.username}};
        
        chatSocket.send(JSON.stringify({

            'message': message,
            'user':user,
            'pk_mensaje': pk_mensaje,
            'tema_seleccionado':tema_seleccionado,
            'tipo_user':tipo_user,
           // 'fecha_ultimo_mensaje':fecha_ultimo_mensaje

        }));

        chatSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            var message = data['message'];
            if(message == 'El usuario se ha desconectado'){
                enviarInicio();
            }
            var txtarea = document.getElementById("texto_mensaje");
            document.querySelector('#texto_mensaje').value += (message + '\n');
            if(txtarea.selectionStart == txtarea.selectionEnd) {
                txtarea.scrollTop = txtarea.scrollHeight;
            }
            
            //document.getElementById("texto_mensaje").scrollTop = document.getElementById("#texto_mensaje").scrollHeight
            var d = new Date();
        //    fecha_ultimo_mensaje= (' '+ d.getMonth()+'/'+d.getDay()+ '/' + d.getFullYear()+' '+d.getHours()+':'+d.getMinutes());
            console.log("Connected to chat socket");
            
        };
    
        chatSocket.onclose = function(e) {
    
            var message='Usuario '+ '{{user.username}}' + ' ha salido de la conversación \n ';
            chatSocket.send(JSON.stringify({
                'message': message,
                'pk_mensaje': pk_mensaje,
                'tipo_user':tipo_user,
                'importante':importante,
        //        'fecha_ultimo_mensaje':fecha_ultimo_mensaje
    
            }));
            console.error('Chat socket closed unexpectedly');
            console.log("Disconnected from chat socket");
    
        };
        
        messageInputDom.value = '';
        
    };
</script>
</html>
{% endblock %}