SisSerSocMedHumUAZ-master/rol/urls.py
from django.conf.urls import url

from rol.views import *

urlpatterns = [
    url(r'^registrar_rol/$', CrudRol.registrar_rol, name="registrar_rol"),
    url(r'^modificar_rol/$', CrudRol.modificar_rol, name="modificar_rol"),
    url(r'^roles/$', CrudRol.mostrar_roles, name="roles"),
    url(r'^eliminar_rol/$', CrudRol.eliminar_rol, name="eliminar_rol"),
    url(r'^tutores/$', CrudTutor.mostrar_tutores, name="tutores"),
    url(r'^eliminar_tutor/$', CrudTutor.eliminar_tutor, name="eliminar_tutor"),
    url(r'^modificar_tutor/$', CrudTutor.modificar_tutor,
        name="modificar_tutor"),
    url(r'^registrar_tutor/$', CrudTutor.registrar_tutor,
        name="registrar_tutor"),
    url(r'^asignar_rol/$', AsignacionRolPasante.asignar_rol,
        name='asignar_rol'),
    url(r'^rol_pasante_json/$', AsignacionRolPasante.rol_pasante_json,
        name='rol_pasante_json'),
    url(r'^modificar_asignacion/$', AsignacionRolPasante.modificar_asignacion,
        name='modificar_asignacion'),
    url(r'^carta_asignacion/$', AsignacionRolPasante.carta_asignacion,
        name='carta_asignacion'),
    url(r'^clinicas_institucion/$', obtener_clinicas),
    url(r'^carta_asignacion_oficial/$',
        AsignacionRolPasante.carta_asignacion_oficial,
        name='carta_asignacion_oficial'),
    url(r'configuracion_asignacion', AsignacionRolPasante.configurar_asignacion,
        name='configuracion_asignacion'),
]

SisSerSocMedHumUAZ-master/ssmh_uaz_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from contactos_pasante import  views



urlpatterns = [
    url(r'^chat/', include('mensajeria.urls')),
    url(r'^', include('usuario.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^Pasante/',include('pasante.urls')),
    url(r'^Coordinador/',include('coordinador.urls')),
    #url(r'^SuperUsuario/',include('SuperUsuario.urls')),
    url(r'^Rol/',include('rol.urls')),
    url(r'^foro/',include('foro.urls')),
    url(r'^Pregunta/',include('pregunta.urls')),

    url(r'^api/contacto/obtenerContactos/(?P<idPasante>.+)/$', views.GetContactos.as_view(), name='obtener_contactos'),
    url(r'^api/contacto/insertarContacto', views.InsertContacto.as_view(), name='insertar_contacto'),
    url(r'^api/contacto/eliminarContacto/(?P<idContacto>[0-9]+)/$', views.EliminarContacto.as_view(), name='eliminar_contacto'),
    url(r'^api/contacto/actualizarContacto/(?P<idContacto>[0-9]+)/$', views.ActualizarContacto.as_view(), name='actualizar_contacto'),
    url(r'^api/usuario/verificarUsuario/$', views.VerificarUsuario.as_view(), name='verificar_usuario'),
    url(r'^api/usuario/activaralerta$', views.ActivarAlerta.as_view(), name='alerta'),
    url(r'^api/usuario/informacionPasante/$', views.InformacionPasante.as_view()),
    url(r'^api/usuario/enviarMensaje/$', views.EnviarMensaje.as_view(), name='Enviar Mensaje'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SisSerSocMedHumUAZ-master/usuario/urls.py
from django.conf.urls import include, url
from usuario.views import loginpos,AltaUsuario,IniciaSesion, SesionExperto
from django.contrib.auth.views import login, logout_then_login


urlpatterns = [
    url(r'^logout/$', logout_then_login, name="logout_user"),
    url(r'^$', IniciaSesion.iniciar_sesion, name="iniciar_sesion"),
    url(r'^registrar$', AltaUsuario.registrar_usuario, name='usuario_nuevo'),
    url(r'^recuperar$', IniciaSesion.recuperar_contrasena, name='recuperar_contrasena'),
	url(r'experto$', SesionExperto.iniciar_sesion_experto, name="experto"),
	url(r'experto2$', SesionExperto.iniciar_sesion, name="experto2"),


]

SisSerSocMedHumUAZ-master/usuario/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Usuario(User):
    id_usuario = models.AutoField(primary_key=True)
    matricula = models.CharField(max_length=8, unique=True)
    contrasena = models.CharField(max_length=128)
    tipo_usuario = models.CharField(max_length=50)
    correo_electronico = models.CharField(unique=True, max_length=250)
    correo_institucional = models.CharField(max_length=250)


'''
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Usuario(User):
    id_usuario = models.AutoField(primary_key=True)
    matricula = models.CharField(u'matricula', max_length=8, unique=True)
    contrasena = models.CharField(u'contrasena', max_length=128)
    tipo_usuario = models.CharField(u'tipo_usuario', max_length=50)
    correo_electronico = models.CharField(u'correo_electronico', unique=True,
                                          max_length=250)
    correo_institucional = models.CharField(u'correo_institucional',
                                            max_length=250)

'''

SisSerSocMedHumUAZ-master/usuario/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.forms import TextInput
from django.contrib.auth.models import User
from django.forms import ModelForm
from usuario.models import Usuario

	#modelos de usario

class FormUsuario(forms.ModelForm):
	

	matrícula = forms.CharField(max_length=8,widget=forms.TextInput(attrs={'onkeypress':'return justNumbers(event);','title':'Ingresa tu matrícula*','oninput':'check_textm(this);'}),label='Matrícula*',required=False)
	password = forms.CharField(widget=forms.PasswordInput(attrs={'title':'Ingresa tu contraseña*'}),label='Contraseña*')
	confirmar_password = forms.CharField(widget=forms.PasswordInput(attrs={'title':'Confirma tu contraseña*'}),required=True, max_length=50,label='Confirma tu contraseña*')
	correo_electrónico = forms.EmailField(required = True, max_length=50,widget=forms.EmailInput(attrs={'title':'Ingresa tu correo electronico principal*'}),label='Correo electrónico principal*')
	correo_institucional = forms.EmailField(required=False,max_length=50,widget=forms.EmailInput(attrs={'title':'Ingresa un correo alternativo*'}),label='Correo electrónico alternativo')

	class Meta:
         model = Usuario
         fields = ()

SisSerSocMedHumUAZ-master/usuario/views.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
import json
import urllib

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.mail import EmailMessage, send_mail, EmailMultiAlternatives
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from usuario.models import Usuario
from coordinador.models import fecha_registro
from django.contrib.auth.hashers import *
from random import choice
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib.auth.forms import UserCreationForm
from datetime import datetime, timedelta, date
from usuario.forms import FormUsuario
from ssmh_uaz_project import settings
import re

registro = {}
registro_fallido = False
registro_fallido_experto = False


# Create your views here.
def loginpos(request):
    return render(request, 'iniciarsesion.html')	
class IniciaSesion:
    def recuperar_contrasena(request):
        if request.method != 'POST':
            return render(request, 'recuperar.html')
        mat = request.POST.get('matricula')
        correo = request.POST.get('correo')
        if mat == "" or correo == "":
            funcion = "Debe escribir su correo y matrícula."
            return render(request, 'recuperar.html', {'funcion': funcion})
        longitud = 7
        valores = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

        p = ""
        p = p.join([choice(valores) for i in range(longitud)])

        try:
            user = Usuario.objects.get(matricula=mat, correo_electronico=correo)
            message = "Tu contraseña nueva es la siguiente:    "
            message += p
            subject = 'Recuperación de contraseña'
            text_content = 'Recuperacion de contraseña'
            html_content = '<h2>Recuperación de contraseña</2><p>Medicina humana<br>Uaz</p><br> <h2 style="font-family: Andale Mono,AndaleMono,monospace; font-size:16px; font-style:normal;">' + message + '</h2>'
            from_email = '"SCSSUAMH" <ssmh.uaz@gmail.com>'
            msg = EmailMultiAlternatives(subject, text_content, from_email,
                                         [user.correo_electronico])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            user.password = make_password(p)
            user.contrasena = make_password(p)
            # usuario=user(password = make_password(password),contrasena = make_password(password))
            user.save()

            formulario = FormUsuario()
            return render(request, 'iniciarsesion.html',
                          {'exito': 'Se envío una nueva contraseña al correo.',
                           'formulario': formulario})

        except:

            formulario = FormUsuario()
            return render(request, 'iniciarsesion.html', {
                'funcion': 'Matricula invalida y/o correo revisa tus datos.',
                'formulario': formulario})

    def iniciar_sesion(request):
        user = request.user

        if user is not None and user.is_authenticated and user.is_active:
            if user.is_staff:
                print('redireccionar a inicio coordinador')
                return redirect('inicio')
            else:
                print('redireccionar a inicio pasante')
                return redirect('inicio_pasante')
            
        global registro_fallido
        BajaAnual.desactivar_pasante_anual()
        formulario = FormUsuario()
        if (len(registro) > 0):
            registro.clear()
            return render(request, 'iniciarsesion.html',
                          {'exito': 'Se registró al usuario.',
                           'formulario': formulario})
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = ""
        print(registro_fallido == True)
        if registro_fallido:
            if username == None:
                return render(request, 'iniciarsesion.html',
                              {'formulario': formulario,
                               'login_fallido': "El campo matrícula no debe ser vacío."})
            if password == None:
                return render(request, 'iniciarsesion.html',
                              {'formulario': formulario,
                               'login_fallido': "El campo contraseña no debe ser vacío."})

        if (username != None and password != None):
            user = authenticate(username=username, password=password)

        if user is not None:
            try:
                datos_usuario = Usuario.objects.get(matricula=username)
            except Exception as e:
                return render(request, 'iniciarsesion.html',
                              {'formulario': formulario})
            if datos_usuario.is_staff == 1:
                login(request, user)
                return HttpResponseRedirect('/Coordinador/inicio/')
            else:
                login(request, user)
                return HttpResponseRedirect('/Pasante/inicio/')
        else:

            if username == "" or password == "":
                if username == "":
                    return render(request, 'iniciarsesion.html',
                                  {'formulario': formulario,
                                   'login_fallido': "El campo matrícula no debe ser ser vacío."})
                if password == "":
                    return render(request, 'iniciarsesion.html',
                                  {'formulario': formulario,
                                   'login_fallido': "El campo contraseña no debe ser vacío."})
            else:
                return render(request, 'iniciarsesion.html',
                              {'formulario': formulario,
                               'login_fallido': "Los datos introducidos son incorrectos."})
							   
	
	

class SesionExperto:
    def iniciar_sesion_experto(request):
        if request.method != 'POST':
		       return render(request, 'iniciarsesionexp.html')

           
    def iniciar_sesion(request):
        user = request.user
        global registro_fallido_experto
        formulario = FormUsuario()

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
   
        if user is not None:
          datos_usuario = Usuario.objects.filter(correo_electronico=username)
          messages.success(request, 'Bienvenido al Foro')

          login(request, user)

          return HttpResponseRedirect('foro')

        else:
          return render(request, 'iniciarsesionexp.html', {'formulario': formulario,
                                  'login_fallido': "Datos Incorrectos / Datos Faltantes."})
        
class AltaUsuario:
    def registrar_usuario(request):

        if request.method == 'POST':
            formulario = FormUsuario(request.POST)

            try:
                if formulario.is_valid:

                    recaptcha_response = request.POST.get(
                        'g-recaptcha-response')
                    url = 'https://www.google.com/recaptcha/api/siteverify'
                    values = {
                        'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                        'response': recaptcha_response
                    }
                    data = urllib.parse.urlencode(values).encode()
                    req = urllib.request.Request(url, data=data)
                    response = urllib.request.urlopen(req)
                    result = json.loads(response.read().decode())

                    matricula = request.POST.get('matrícula')
                    password = request.POST.get('password')
                    password2 = request.POST.get('confirmar_password')
                    email = request.POST.get('correo_electrónico')
                    email2 = request.POST.get('correo_institucional')

                    if matricula == "":
                        return render(request, 'registrar.html',
                                      {'formulario': formulario,
                                       'funcion': 'El campo de "Matrícula" no debe estar vacío.',
                                       "matricula": matricula, "email": email,
                                       "email2": email2})
                    if (len(matricula) != 8):
                        return render(request, 'registrar.html',
                                      {'formulario': formulario,
                                       'funcion': 'La "Matrícula" debe cumplir con 8 caracteres numéricos.',
                                       "matricula": matricula, "email": email,
                                       "email2": email2})

                    try:
                        int(matricula)
                    except ValueError:
                        return render(request, 'registrar.html',
                                      {'formulario': formulario,
                                       'funcion': 'La "Matrícula" debe cumplir con 8 caracteres numéricos.',
                                       "matricula": matricula, "email": email,
                                       "email2": email2})
                    # validacion de la matricula, para comprobar que son solo numeros
                    # import pdb;
                    # pdb.set_trace()
                    if Usuario.objects.filter(matricula=matricula).exists():
                        return render(request, 'registrar.html',
                                      {'formulario': formulario,

SisSerSocMedHumUAZ-master/usuario/templates/registrar.html
<div class="intro-conten" >
{% extends 'baseusuario.html' %}

{% block encabezado %}
  <h1>Registra un nuevo usuario</h1>
{% endblock %}

{% block contenido %}
<script type="text/javascript"> 
function redireccionarPagina() {
  window.location = "/";
  
}

</script>



<style type="text/css">
table{
    width: 350px;
    height: 100px;
}
</style>
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:400,300,100,700,500);


@-webkit-keyframes HeroBG {
  0% {
    background-position: 0 0;
  }
  50% {
    background-position: 100% 0;
  }
  100% {
    background-position: 0 0;
  }
}

@keyframes HeroBG {
  0% {
    background-position: 0 0;
  }
  50% {
    background-position: 100% 0;
  }
  100% {
    background-position: 0 0;
  }
}



.panel {
  border-radius: 5px;
}
label {
  font-weight: 300;
}
.panel-login {
   border: none;
  -webkit-box-shadow: 0px 0px 49px 14px rgba(188,190,194,0.39);
  -moz-box-shadow: 0px 0px 49px 14px rgba(188,190,194,0.39);
  box-shadow: 0px 0px 49px 14px rgba(188,190,194,0.39);

  }
.panel-login .checkbox input[type=checkbox]{
  margin-left: 0px;
}
.panel-login .checkbox label {
  padding-left: 25px;
  font-weight: 300;
  display: inline-block;
  position: relative;
}
.panel-login .checkbox {
 padding-left: 20px;
}
.panel-login .checkbox label::before {
  content: "";
  display: inline-block;
  position: absolute;
  width: 17px;
  height: 17px;
  left: 0;
  margin-left: 0px;
  border: 1px solid #cccccc;
  border-radius: 3px;
  background-color: #fff;
  -webkit-transition: border 0.15s ease-in-out, color 0.15s ease-in-out;
  -o-transition: border 0.15s ease-in-out, color 0.15s ease-in-out;
  transition: border 0.15s ease-in-out, color 0.15s ease-in-out;
}
.panel-login .checkbox label::after {
  display: inline-block;
  position: absolute;
  width: 16px;
  height: 16px;
  left: 0;
  top: 0;
  margin-left: 0px;
  padding-left: 3px;
  padding-top: 1px;
  font-size: 11px;
  color: #555555;
}
.panel-login .checkbox input[type="checkbox"] {
  opacity: 0;
}
.panel-login .checkbox input[type="checkbox"]:focus + label::before {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
.panel-login .checkbox input[type="checkbox"]:checked + label::after {
  font-family: 'FontAwesome';
  content: "\f00c";
}
.panel-login>.panel-heading .tabs{
  padding: 0;
}
.panel-login h2{
  font-size: 20px;
  font-weight: 300;
  margin: 30px;
}
.panel-login>.panel-heading {
  color: #848c9d;
  background-color: #e8e9ec;
  border-color: #fff;
  text-align:center;
  border-bottom-left-radius: 5px;
  border-bottom-right-radius: 5px;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom: 0px;
  padding: 0px 15px;
}
.panel-login .form-group {
  
}
.panel-login>.panel-heading .login {
  padding: 20px 30px;
  border-bottom-leftt-radius: 5px;
}
.panel-login>.panel-heading .register {
  padding: 20px 50px;
  background: #2d3b55;
  border-bottom-right-radius: 5px;
}
.panel-login>.panel-heading a{
  text-decoration: none;
  color: #666;
  font-weight: 300;
  font-size: 16px;
  -webkit-transition: all 0.1s linear;
  -moz-transition: all 0.1s linear;
  transition: all 0.1s linear;
}
.panel-login>.panel-heading a#register-form-link {
  color: #fff;
  width: 100%;
  text-align: left;
}
.panel-login>.panel-heading a#login-form-link {
  width: 100%;
  text-align: left;
}

.panel-login input[type="text"],.panel-login input[type="email"],.panel-login input[type="password"] {
  height: 45px;
  border: 0;
  font-size: 16px;
  -webkit-transition: all 0.1s linear;
  -moz-transition: all 0.1s linear;
  transition: all 0.1s linear;
  -webkit-box-shadow: none;
  box-shadow: none;
  border-bottom: 1px solid #e7e7e7;
  border-radius: 0px;
  padding: 6px 20px;
  border-bottom-color: black;

}

.panel-login input:hover,
.panel-login input:focus {
  outline:none;
  -webkit-box-shadow: none;
  -moz-box-shadow: none;
  box-shadow: none;
  border-color: #ccc;
}
.btn-login {
  background-color: #E8E9EC;
  outline: none;
  color: #2D3B55;
  font-size: 14px;
  height: auto;
  font-weight: normal;
  padding: 14px 0;
  text-transform: uppercase;
  border: none;
  border-radius: 0px;
  box-shadow: none;
}
.btn-login:hover,
.btn-login:focus {
  color: #fff;
  background-color: #2D3B55;
}
.forgot-password {
  text-decoration: underline;
  color: #888;
}
.forgot-password:hover,
.forgot-password:focus {
  text-decoration: underline;
  color: #666;
}

.btn-register {
  background-color: #E8E9EC;
  outline: none;
  color: #2D3B55;
  font-size: 14px;
  height: auto;
  font-weight: normal;
  padding: 14px 0;
  text-transform: uppercase;
  border: none;
  border-radius: 0px;
  box-shadow: none;
}
.btn-register:hover,
.btn-register:focus {
  color: #fff;
  background-color: #2D3B55;
}

label,
input,
button,
select,
textarea {
  font-family: 'Open Sans', sans-serif;
  font-size: inherit;
  line-height: inherit;
  color: black;
  font-weight: 500;
}
input{
  width: 100%;
  margin-bottom: 3px;


}
</style>

{% if user.is_authenticated %}
    {% if request.user.is_active and request.user.is_staff %}
        <h1>Error 404 no se encontró la página solicitada</h1>
        <br>
        <a href="{% url "inicio" %}"><i ></i>ir a inicio</a>
    {% else %}
        <h1>Error 404 no se encontró la página solicitada</h1>
        <br>
        <a href="{% url "inicio_pasante" %}"><i ></i>ir a inicio</a>
    {% endif %}

    {% else %}



    <script type="text/javascript">
    function check_text(input) {  
        if (input.validity.patternMismatch){  
            input.setCustomValidity("La matrícula debe cumplir con 8 caracteres.");  
        }  
        else {  
            input.setCustomValidity("");  
        }                 
    }
    function check_textm(input) {  
        if (input.validity.patternMismatch){  
            input.setCustomValidity("La matrícula debe cumplir con 8 caracteres.");  
        }  
        else {  
            input.setCustomValidity("");  
        }                 
    } 
    </script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript">
$(function() {
    
    $('#login-form-link').click(function(e) {
      $("#login-form").delay(100).fadeIn(100);
    $("#register-form").fadeOut(100);
    $('#register-form-link').removeClass('active');
    $(this).addClass('active');
    e.preventDefault();
  });
  $('#register-form-link').click(function(e) {
    $("#register-form").delay(100).fadeIn(100);
    $("#login-form").fadeOut(100);
    $('#login-form-link').removeClass('active');
    $(this).addClass('active');
    e.preventDefault();
  });

});

  
</script>
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<div class="container">
  
   <div class="row">
   
    <div class="col-md-6 col-md-offset-3">
    {% if funcion != null %}
      <div class="alert alert-danger">{{funcion}}</div>
      <script type="text/javascript">
        
          
          $('#login-form-link').removeClass('active');
          $('#register-form-link').addClass('active');
         
       
        #setTimeout("redireccionarPagina()", 5000);
      
      </script>
    {% endif %}
    {% if exito != null %}
      <div class="alert alert-success">{{exito}}</div>
      <script type="text/javascript">
      
        #setTimeout("redireccionarPagina()", 5000);
      
      </script>
    {% endif %}
    
      <div class="panel panel-login" style="background-color: rgba(192, 201, 227, 0.47); box-shadow: 0px 0px 49px 14px rgba(1, 11, 33, 0.39);
">  


    <div class="panel-heading">
          <div class="row">
            <div class="col-xs-6 tabs">
              <a href="{% url "iniciar_sesion" %}" class="active" id=""><div class="login" >Ingresar</div></a>
            </div>
            <div class="col-xs-6 tabs">
              <a href="{% url "usuario_nuevo" %}" id=""><div class="register" style="color:#ffffff";>Crear Cuenta</div></a>
            </div>
          </div>
        </div>
        <div class="panel-body" style="background-color:rgba(192, 201, 227, 0.47);>

          <div class="row">
          {% if login_fallido != null %}
            <div class="alert alert-danger">
            
          {{login_fallido}}
      </div>
      
    {% endif %}
            <div class="col-lg-12">
              <form id="login-form" action ="{% url "usuario_nuevo" %}" method="post" role="form" style="display: block;">

                            {% csrf_token %}
                  
                  <div class="form-group" style="overflow-x:auto;">
                   <center><table style="border-collapse: collapse;border-spacing: 0;width: 100%;text-align:center;overflow-x:auto" >


                  <table style="border-collapse: collapse;border-spacing: 0;width: 100%;text-align:center;overflow-x:auto">

                  <tbody>
                    <tr>
                      <th>
                          <label for="id_matrícula">Matrícula: *</label>
                      </th>
                      <td>
                          <input id="id_matrícula" maxlength="8" name="matrícula" title="Ingresa tu matricula" type="text" value="{{matricula}}">
                      </td>
                    </tr>
                    
                    <tr>
                      <th>
                        <label for="id_password">Contraseña: *</label>
                      </th>
                      <td> 
                        <input id="id_password" name="password" title="Ingresa tu contraseña*" type="password" >
                      </td>
                    </tr>

                    <tr>
                      <th>
                        <label for="id_confirmar_password">Confirma tu contraseña: *</label>
                      </th>
                      <td>
                        <input id="id_confirmar_password" maxlength="50" name="confirmar_password" title="Confirma tu contraseña*" type="password" >
                      </td>
                    </tr>

                    <tr>
                      <th>
                        <label for="id_correo_electrónico">Correo electrónico principal: *</label>
                      </th>
                      <td>
                        <input id="id_correo_electrónico" maxlength="50" name="correo_electrónico" title="Ingresa tu correo electronico principal*" type="text" value="{{email}}">
                      </td>
                    </tr>

                    <tr>
                      <th>
                        <label for="id_correo_institucional">Correo electrónico alternativo:</label>
                      </th>
                      <td>
                        <input id="id_correo_institucional" maxlength="50" name="correo_institucional" title="Ingresa un correo alternativo*" type="text" value="{{email2}}">
                      </td>
                    </tr>

                    
                      
                  
                  
                  
                  
                  
                  
                  
                  
                  



                   </table></center> 
                  </div>
                  <div class="form-group">
                    <div class="col-sm-8 col-sm-offset-2" >
                        <script src='https://www.google.com/recaptcha/api.js'></script>
                        <div class="g-recaptcha" data-sitekey="6LevQH8UAAAAAHof3npn7a1FiCVlQOGO87rKVBW_"></div>
                    </div>
                  </div>
                  <div class="form-group" >
                    <div class="row"  >
                      <div class="col-sm-6 col-sm-offset-3" >              
                        <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Crear Cuenta" >
                      </div>
                    </div>
                  </div>
              </form>
            </div>
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>
{% endif %}




{% endblock %}
</div>